name: Test1

on: [push, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage coveralls
        
    - name: Run tests with coverage
      run: |
        coverage run -m pytest test.py
    
    - name: Run tests
      run: |
        pytest test.py
        
    - name: Submit coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_SECRET }}
      run: |
        coveralls
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=reknik16_test1
          -Dsonar.organization=reknik16
          -Dsonar.sources=.
          -Dsonar.python.coverage.reportPaths=coverage.xml 
